{{ if .Values.buildnum.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "buildnum.name" . }}
  labels:
    app: {{ template "buildnum.name" . }}
spec:
  replicas: 1 # one canonical source of build numbers
  selector:
    matchLabels:
      app: {{ template "buildnum.name" . }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
{{- if .Values.buildnum.datadog.enabled }}
      annotations:
        ad.datadoghq.com/buildnum.logs: '[{"source":"prow","service":"buildnum"}]'
{{- end }}
      labels:
        app: {{ template "buildnum.name" . }}
    spec:
      serviceAccountName: {{ template "buildnum.name" . }}
      terminationGracePeriodSeconds: {{ .Values.buildnum.terminationGracePeriodSeconds }}
      containers:
      - name: {{ template "buildnum.name" . }}
        image: {{ .Values.buildnum.image.repository }}:{{ .Values.buildnum.image.jxTag }}
        imagePullPolicy: {{ .Values.buildnum.imagePullPolicy }}
{{ if .Values.buildnum.command }}
        command:
{{ toYaml .Values.buildnum.command | indent 10 }}
{{- end }}
{{ if .Values.buildnum.args }}
        args:
{{ toYaml .Values.buildnum.args | indent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.buildnum.resources | indent 10 }}
        ports:
          - name: http
            containerPort: {{ .Values.buildnum.service.internalPort }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.buildnum.probe.livenessPath }}
            port: http
        readinessProbe:
          httpGet:
            path: {{ .Values.buildnum.probe.readinessPath }}
            port: http
{{ end }}
