apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "build.name" . }}
  labels:
    app: {{ template "build.name" . }}
spec:
  replicas: {{ .Values.build.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "build.name" . }}
    spec:
      serviceAccountName: {{ template "build.name" . }}
      terminationGracePeriodSeconds: {{ .Values.build.terminationGracePeriodSeconds }}
      containers:
      - name: {{ template "build.name" . }}
        args:
        - --tot-url
        - http://buildnum
        image: {{ .Values.build.image.repository }}:{{ .Values.build.image.tag }}
        imagePullPolicy: {{ .Values.build.imagePullPolicy }}
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/started
          failureThreshold: {{ .Values.build.failureThreshold }}
          initialDelaySeconds: {{ .Values.build.liveInitialDelaySeconds }}
          periodSeconds: {{ .Values.build.periodSeconds }}
          successThreshold: {{ .Values.build.successThreshold }}
          timeoutSeconds: {{ .Values.build.timeoutSeconds }}
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/started
          failureThreshold: {{ .Values.build.failureThreshold }}
          initialDelaySeconds: {{ .Values.build.readyInitialDelaySeconds }}
          periodSeconds: {{ .Values.build.periodSeconds }}
          successThreshold: {{ .Values.build.successThreshold }}
          timeoutSeconds: {{ .Values.build.timeoutSeconds }}
    {{- with .Values.build.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.build.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.build.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
