apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crier.name" . }}
  labels:
    app: {{ template "crier.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "crier.name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
{{- if .Values.crier.datadog.enabled }}
      annotations:
        ad.datadoghq.com/crier.logs: '[{"source":"prow","service":"crier"}]'
{{- end }}
      labels:
        app: {{ template "crier.name" . }}
    spec:
      serviceAccountName: {{ template "crier.name" . }}
      terminationGracePeriodSeconds: {{ .Values.crier.terminationGracePeriodSeconds }}
      containers:
      - name: {{ template "crier.name" . }}
        image: {{ tpl .Values.crier.image.repository . }}:{{ tpl .Values.crier.image.tag . }}
        imagePullPolicy: {{ .Values.crier.imagePullPolicy }}
{{ if .Values.crier.args }}
        args:
{{ toYaml .Values.crier.args | indent 10 }}
{{- end }}
{{- if .Values.crier.env }}
        env:
{{- range $pkey, $pval := .Values.crier.env }}
        - name: {{ $pkey }}
          value: {{ $pval }}
{{- end }}
{{- end }}
        resources:
{{ toYaml .Values.crier.resources | indent 10 }}
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token
      - name: config
        configMap:
          name: config
