{{ if .Values.horologium.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "horologium.name" . }}
  labels:
    app: {{ template "horologium.name" . }}
spec:
  replicas: {{ .Values.horologium.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "horologium.name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
{{- if .Values.horologium.datadog.enabled }}
      annotations:
        ad.datadoghq.com/horologium.logs: '[{"source":"prow","service":"horologium"}]'
{{- end }}
      labels:
        app: {{ template "horologium.name" . }}
    spec:
      serviceAccountName: {{ template "horologium.name" . }}
      terminationGracePeriodSeconds: {{ .Values.horologium.terminationGracePeriodSeconds }}
      containers:
      - name: {{ template "horologium.name" . }}
        image: {{ tpl .Values.horologium.image.repository . }}:{{ tpl .Values.horologium.image.tag . }}
        imagePullPolicy: {{ .Values.horologium.imagePullPolicy }}
{{- if .Values.horologium.env }}
        env:
{{- range $pkey, $pval := .Values.horologium.env }}
        - name: {{ $pkey }}
          value: {{ $pval }}
{{- end }}
{{- end }}
        resources:
{{ toYaml .Values.horologium.resources | indent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
{{ end }}
