# Default values for prow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deck:
  replicaCount: 2
  probe:
    path: /
  image:
    repository: gcr.io/k8s-prow/deck
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  args:
    - --hook-url=http://hook:8888/plugin-help
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nnginx.ingress.kubernetes.io/auth-type: basic\nnginx.ingress.kubernetes.io/auth-secret: jx-basic-auth"

echotest:
  interval: 10m
  command: /bin/date

tot:
  image:
    repository: gcr.io/k8s-prow/tot
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 180
  args:
    - -storage=/store/tot.json
    - -fallback
  resources:
    limits:
     cpu: 400m
     memory: 256Mi
    requests:
     cpu: 200m
     memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8888
  pvc:
    size: 1Gi

hook:
  replicaCount: 2
  probe:
    path: /
  image:
    repository: gcr.io/k8s-prow/hook
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 180
  args:
    - --dry-run=false
  resources:
    limits:
     cpu: 400m
     memory: 256Mi
    requests:
     cpu: 200m
     memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8888
    annotations:
      fabric8.io/expose: "true"
horologium:
  replicaCount: 1
  image:
    repository: gcr.io/k8s-prow/horologium
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  args:
    - --dry-run=false
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

plank:
  image:
    repository: gcr.io/k8s-prow/plank
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

build:
  image:
    repository: gcr.io/k8s-prow/build
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

sinker:
  replicaCount: 1
  image:
    repository: gcr.io/k8s-prow/sinker
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

plugins:
  yaml: ""

user: james-foo


tide:
  replicaCount: 1
  probe:
    path: /
  image:
    repository: gcr.io/k8s-prow/tide
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  args:
    - --dry-run=false
    #- --github-endpoint=http://ghproxy
    - --github-endpoint=https://api.github.com
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8888
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nnginx.ingress.kubernetes.io/auth-type: basic\nnginx.ingress.kubernetes.io/auth-secret: jx-basic-auth"
