# Default values for prow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deck:
  replicaCount: 2
  probe:
    path: /
  image:
    repository: gcr.io/k8s-prow/deck
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  args:
    - --hook-url=http://hook/plugin-help
    - --tide-url=http://tide
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nnginx.ingress.kubernetes.io/auth-type: basic\nnginx.ingress.kubernetes.io/auth-secret: jx-basic-auth"

echotest:
  interval: 10m
  command: /bin/date

buildnum:
  image:
    repository: jenkinsxio/jx
    jxTag: 1.3.812
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 180
  command:
  - jx
  args:
  - "controller"
  - "buildnumbers"
  resources:
    limits:
     cpu: 400m
     memory: 256Mi
    requests:
     cpu: 200m
     memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8080


crier:
  image:
    repository: docker.io/garethjevans/crier
    tag: upstream03
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 180
  args:
    - -gerrit-workers=0
    - -github-workers=1
    - -logtostderr
    - -config-path=/etc/config/config.yaml
    - -github-token-path=/etc/github/oauth
  resources:
    limits:
     cpu: 400m
     memory: 256Mi
    requests:
     cpu: 200m
     memory: 128Mi

branchprotector:
  enabled: false
  schedule: "54 * * * *"  # Every hour at 54 minutes past the hour
  image:
    repository: gcr.io/k8s-prow/branchprotector
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  args:
    - --config-path=/etc/config/config.yaml
    - --github-token-path=/etc/github/oauth
    - --confirm
    - --github-endpoint=https://api.github.com
  resources:
    limits:
     cpu: 400m
     memory: 256Mi
    requests:
     cpu: 200m
     memory: 128Mi

hook:
  replicaCount: 2
  probe:
    path: /
  image:
    # repository: gcr.io/k8s-prow/hook
    # tag: v20181113-9b11013
    repository: rawlingsj/hook
    tag: upstream56
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 180
  args:
    - --dry-run=false
  resources:
    limits:
     cpu: 400m
     memory: 256Mi
    requests:
     cpu: 200m
     memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8888
    annotations:
      fabric8.io/expose: "true"
horologium:
  replicaCount: 1
  image:
    repository: gcr.io/k8s-prow/horologium
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  args:
    - --dry-run=false
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

plank:
  image:
    repository: gcr.io/k8s-prow/plank
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  args:
    - --dry-run=false
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

build:
  image:
    repository: rawlingsj/build
    tag: upstream125
    # repository: gcr.io/k8s-prow/build
    # tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi
  failureThreshold: 1
  readyInitialDelaySeconds: 5
  liveInitialDelaySeconds: 60
  periodSeconds: 2
  successThreshold: 1
  timeoutSeconds: 1

sinker:
  replicaCount: 1
  image:
    repository: gcr.io/k8s-prow/sinker
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

plugins:
  yaml: ""

user: james-foo


tide:
  replicaCount: 1
  probe:
    path: /
  image:
    repository: rawlingsj/tide
    tag: upstream1
    # repository: gcr.io/k8s-prow/tide
    # tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  args:
    - --dry-run=false
    #- --github-endpoint=http://ghproxy
    - --github-endpoint=https://api.github.com
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8888
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nnginx.ingress.kubernetes.io/auth-type: basic\nnginx.ingress.kubernetes.io/auth-secret: jx-basic-auth"